export interface ProjectImage {
  url: string;
  caption: string;
}

export interface Project {
  id: string;
  title: string;
  location: string;
  year: string;
  area: string;
  category: string;
  client: string;
  status: string;
  description: string;
  challenge: string;
  solution: string;
  tags: string[];
  accentColor: string;
  svgKey: string;
  images: ProjectImage[];
}

export interface Service {
  slug: string;
  label: string;
  title: string;
  subtitle: string;
  description: string;
  tools: string[];
  index: string;
  projects: Project[];
}

// Unsplash placeholder images — architecture themed
const ARCH_IMGS = {
  tower:    [
    { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80", caption: "Street-level elevation — Atlantic facade" },
    { url: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200&q=80", caption: "Parametric facade panel detail" },
    { url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80", caption: "Interior atrium — floor 22" },
    { url: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200&q=80", caption: "Rooftop terrace at dusk" },
  ],
  cultural: [
    { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80", caption: "Main entrance — approach from the east" },
    { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", caption: "Public atrium — natural light study" },
    { url: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?w=1200&q=80", caption: "Gallery wing — exhibition hall" },
    { url: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=1200&q=80", caption: "Structural roof detail" },
  ],
  precinct: [
    { url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=80", caption: "Aerial masterplan view" },
    { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80", caption: "Tower A — commercial podium" },
    { url: "https://images.unsplash.com/photo-1543968996-ee822b8176ba?w=1200&q=80", caption: "Public realm — ground floor activation" },
    { url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80", caption: "Retail street — evening atmosphere" },
  ],
  waterfront: [
    { url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80", caption: "Waterfront promenade at sunrise" },
    { url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&q=80", caption: "Tidal landscape — seasonal flooding study" },
    { url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80", caption: "Pedestrian bridge over the inlet" },
    { url: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?w=1200&q=80", caption: "Mangrove edge — ecological planting" },
  ],
  residence: [
    { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", caption: "Street elevation — golden hour" },
    { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80", caption: "Living room — material palette" },
    { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80", caption: "Master suite — Abeokuta granite detail" },
    { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&q=80", caption: "Pool terrace — Lagos Lagoon view" },
  ],
  arts: [
    { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80", caption: "Presidential entrance hall" },
    { url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80", caption: "Performance hall — acoustic ceiling" },
    { url: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=1200&q=80", caption: "Craft market — ground floor" },
  ],
  library: [
    { url: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200&q=80", caption: "Main reading room — lagoon view" },
    { url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80", caption: "Stack floor — bamboo shelving system" },
    { url: "https://images.unsplash.com/photo-1568667256549-094345857637?w=1200&q=80", caption: "Children's wing — story alcoves" },
    { url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&q=80", caption: "Exterior deck — sunset over the lagoon" },
  ],
  parliament: [
    { url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&q=80", caption: "Chamber hall — civic dignity" },
    { url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", caption: "Rotunda — structural dome" },
    { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80", caption: "Northern facade — approach" },
    { url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80", caption: "Public forecourt — civic plaza" },
  ],
  hotel: [
    { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80", caption: "Lobby — terracotta and timber palette" },
    { url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80", caption: "Suite interior — Akwete textile panels" },
    { url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=80", caption: "Restaurant — Kalakuta music room" },
    { url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80", caption: "Rooftop pool — Port Harcourt skyline" },
  ],
  interiorDesign: [
    { url: "/3d-modeling/3d-1.webp", caption: "Lobby — terracotta and timber palette" },
    { url: "/interior/in-2.jpeg", caption: "Suite interior — Akwete textile panels" },
    { url: "/interior/in-1.jpeg", caption: "Lobby — terracotta and timber palette" },
    { url: "/interior/in-3.jpeg", caption: "Restaurant — Kalakuta music room" },
    { url: "/interior/in-4.jpeg", caption: "Rooftop pool — Port Harcourt skyline" },
  ],
  landscape: [
    { url: "/landscaping/lan-3.jpeg", caption: "RCCG church landscape" },
    { url: "/landscaping/lan-4.jpeg", caption: "RCCG church landscape" },
    { url: "/landscaping/lan-1.jpeg", caption: "Residential landscape" },
    { url: "/landscaping/lan-2.jpeg", caption: "RCCG church landscape" },
    { url: "/landscaping/lan-5.jpeg", caption: "Residential landscape" },
  ],
  residential: [
    { url: "/residential-2/resid-1.jpeg", caption: "Residential building" },
    { url: "/residential-2/resid-2.jpeg", caption: "Residential building" },
    { url: "/residential-2/resid-3.jpeg", caption: "Residential building" },
    { url: "/residential-2/resid-4.jpeg", caption: "Residential building" },
    { url: "/residential-3/resid-1.jpeg", caption: "Residential building" },
    { url: "/residential-3/resid-2.jpeg", caption: "Residential building" },
    { url: "/residential-3/resid-3.jpeg", caption: "Residential building" },
    { url: "/residential-3/resid-4.jpeg", caption: "Residential building" },

  ],
  school: [
    { url: "/school/sch-1.jpeg", caption: "School building" },
    { url: "/school/sch-2.jpeg", caption: "School building" },
  ],
  residentialVisualization: [
    { url: "/3d-visualization/res-vis-1.jpeg", caption: "Residential visualization" },
    { url: "/3d-visualization/res-vis-2.jpeg", caption: "Residential visualization" },
    { url: "/3d-visualization/res-vis-3.jpeg", caption: "Residential visualization" },
    { url: "/3d-visualization/res-vis-4.jpeg", caption: "Residential visualization" },
  ],
  animationOne: [
    { url: "/animation/anim-1.mp4", caption: "Animation" },
    // { url: "/animation/anim-3.jpeg", caption: "Animation" },
    // { url: "/animation/anim-4.jpeg", caption: "Animation" },
  ],
  animationTwo: [
    { url: "/animation/anim-2.mp4", caption: "Animation" },
    // { url: "/animation/anim-3.jpeg", caption: "Animation" },
    // { url: "/animation/anim-4.jpeg", caption: "Animation" },
  ],
  presentationOne: [
    { url: "/presentation/box-and-earth-solutions/pr-2.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-3.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-1.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-4.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-5.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-6.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-7.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-8.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-9.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-10.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-11.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-12.png", caption: "Presentation" },
    { url: "/presentation/box-and-earth-solutions/pr-13.png", caption: "Presentation" },
 
  ],
  presentationTwo: [
    { url: "/presentation/obrutche/ob-1.png", caption: "Presentation" },
    { url: "/presentation/obrutche/ob-2.png", caption: "Presentation" },
    { url: "/presentation/obrutche/ob-3.png", caption: "Presentation" },
  ],
  avenueRow: [
    { url: "/presentation/avenue-row/av-1.png", caption: "Pressentation"},
    { url: "/presentation/avenue-row/av-2.png", caption: "Pressentation"},
    { url: "/presentation/avenue-row/av-3.png", caption: "Pressentation"},
  ]
};

export const SERVICES: Service[] = [
  {
    slug: "3d-modeling",
    label: "3D Modeling",
    title: "3D Modeling",
    subtitle: "Digital form, precision geometry",
    description:
      "BIM-coordinated digital models built from first principles — from early massing studies through fully resolved parametric models ready for fabrication, engineering coordination, and downstream visualization pipelines. Every model carries the intelligence of the design.",
    tools: ["Revit", "Rhino 3D", "Grasshopper", "ArchiCAD", "SketchUp", "Blender"],
    index: "01",
    projects: [
      {
        id: "nm-01",
        title: "Hotel and Hospitality",
        location: "Lagos, Nigeria",
        year: "2023",
        area: "15,000 m²",
        category: "Hospitality",
        client: "Luxury Hotels Group",
        status: "Completed",
        description: "Comprehensive 3D modeling for a luxury hotel and resort complex, focusing on guest experience, spatial flow, and premium amenity integration.",
        challenge: "Balancing the need for high-density room layouts with the expectation of expansive, luxurious communal spaces while maintaining structural efficiency.",
        solution: "Our Revit and Rhino-driven models allowed for rapid iteration of floor plans, optimizing sightlines from suites and ensuring structural alignment across the podium and tower sections.",
        tags: ["Hospitality", "Resort", "Spatial Planning"],
        accentColor: "from-[#1a100a] via-[#2d1800] to-[#0e0a04]",
        svgKey: "tower",
        images: ARCH_IMGS.hotel,
      },
      {
        id: "nm-02",
        title: "Commercial Property",
        location: "Lagos, Nigeria",
        year: "2022",
        area: "24,000 m²",
        category: "Commercial",
        client: "Prime Real Estate Mgt",
        status: "Completed",
        description: "Intricate 3D BIM coordination for a modern commercial office complex featuring open-plan workspaces, retail podiums, and an energy-efficient glass facade.",
        challenge: "Integrating complex MEP systems within a restricted ceiling plenum without compromising the sleek, modern aesthetic requested by the client.",
        solution: "Utilized federated BIM models to perform precise clash detection between structural steelwork, ducting, and architectural finishes, ensuring a zero-clash construction phase.",
        tags: ["Commercial", "Office Space", "BIM Integration"],
        accentColor: "from-[#0a0e18] via-[#0e1626] to-[#060a12]",
        svgKey: "cultural",
        images: ARCH_IMGS.school,
      },
      {
        id: "nm-03",
        title: "Residential Buildings",
        location: "Lagos, Nigeria",
        year: "2022",
        area: "12,500 m²",
        category: "Residential",
        client: "Urban Living Developers",
        status: "Under Construction",
        description: "Detailed 3D models for a high-end multi-family residential block, optimizing natural light, ventilation, and premium living configurations.",
        challenge: "Achieving acoustic privacy and maximizing individual unit floor area within a constrained urban footprint.",
        solution: "Parametric space layout tools in Grasshopper were used to generate unit variations that maximized internal volume and strictly adhered to building setback regulations.",
        tags: ["Residential", "Appartments", "Urban Housing"],
        accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
        svgKey: "precinct",
        images: ARCH_IMGS.residential,
      },
      {
        id: "nm-04",
        title: "Landscaping",
        location: "Lagos, Nigeria",
        year: "2021",
        area: "8.5 ha",
        category: "Landscape Public Realm",
        client: "Private Client",
        status: "Completed",
        description: "Advanced 3D terrain and landscape modeling for a large public park, integrating indigenous planting palettes, water management features, and pedestrian pathways.",
        challenge: "Accurately modeling the complex undulating topography to manage stormwater runoff effectively during heavy rainy seasons.",
        solution: "Imported drone survey data into Rhino to create accurate topographical meshes, allowing for precise cut-and-fill analysis and the design of natural swales.",
        tags: ["Landscape Design", "Topography", "Public Space"],
        accentColor: "from-[#100c08] via-[#1e1608] to-[#0c0a04]",
        svgKey: "waterfront",
        images: ARCH_IMGS.landscape,
      },
    ],
  },
  {
    slug: "3d-visualization",
    label: "3D Visualization",
    title: "3D Visualization",
    subtitle: "Light, material, atmosphere",
    description:
      "Photorealistic CGI renders calibrated to the specific quality of West African light — the angle, the intensity, the way terracotta dust softens a late-afternoon facade. Exterior and interior stills, material studies, lighting scenarios, and context composites for client presentations and planning submissions.",
    tools: ["V-Ray", "Corona Renderer", "Lumion", "Enscape", "Adobe Photoshop", "DaVinci Resolve"],
    index: "02",
    projects: [
      {
        id: "viz-01",
        title: "Ikoyi Residence VII",
        location: "Lagos, Nigeria",
        year: "2023",
        area: "1,800 m²",
        category: "Residential",
        client: "Private Client",
        status: "Completed",
        description: "Twelve hero renders for a luxury Ikoyi residence. The visualization brief was to capture the building at the precise golden hour that frames the Lagos Lagoon.",
        challenge: "The client wanted images that felt like photographs, not renders — specifically the hazy, warm quality of late afternoon Lagos light that experienced photographers spend hours waiting for.",
        solution: "On-site HDRI captures were made at the Ikoyi waterfront at 5:30pm over three consecutive days. The resulting lighting data was used directly in V-Ray, with atmospheric scattering tuned to replicate the specific humidity and dust conditions of the Lagos dry season.",
        tags: ["Luxury Residential", "Exterior Renders", "Golden Hour"],
        accentColor: "from-[#120808] via-[#200e10] to-[#0e0608]",
        svgKey: "residence",
        images: ARCH_IMGS.residence,
      },
      {
        id: "viz-02",
        title: "National Arts & Culture Centre",
        location: "Abuja, Nigeria",
        year: "2023",
        area: "24,000 m²",
        category: "Civic",
        client: "Federal Ministry of Culture",
        status: "Completed",
        description: "Competition submission package of 24 CGI images across exterior approach, arrival sequence, public atrium, and key interior spaces. Won the client presentation and secured planning approval.",
        challenge: "A federal government building must project civic authority without being intimidating — and the CGI had to make this tonal balance visible and convincing to a non-architectural audience.",
        solution: "Images were composed using pedestrian eye-level cameras throughout, with figures representing a full cross-section of Nigerian society. Material colours were carefully desaturated to read as stone and terracotta rather than plastic — a common render failure mode.",
        tags: ["Competition", "Civic", "Series Render"],
        accentColor: "from-[#0a0e18] via-[#0e1626] to-[#060a12]",
        svgKey: "arts",
        images: ARCH_IMGS.arts,
      },
      {
        id: "viz-03",
        title: "Estate Residential Building",
        location: "Lagos, Nigeria",
        year: "2021",
        area: "3,200 m²",
        category: "Residential",
        client: "Private Client",
        status: "Planning Approved",
        description: "Residential building in a gated community in Lagos, Nigeria.",
        challenge: "Convincing water simulation that captured both the mirror-like stillness of the lagoon at dusk and the complex caustic patterns of daylight on the underside of the floating structure.",
        solution: "Phoenix FD fluid simulation was used for water surface animation, baked down for the still renders. Caustic patterns were captured from a physical water tray under controlled lighting and projected onto the structure's underside in compositing.",
        tags: ["Atmosphere", "Water Reflections", "Cultural"],
        accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
        svgKey: "library",
        images: ARCH_IMGS.residentialVisualization,
      },
      {
        id: "viz-05",
        title: "Kalakuta Suite Hotel",
        location: "Port Harcourt, Nigeria",
        year: "2021",
        area: "6,400 m²",
        category: "Hospitality",
        client: "Kalakuta Hospitality Group",
        status: "Completed",
        description: "Interior and exterior visualization package for a boutique hotel referencing Fela Kuti's legacy. Warm material palette required careful balance between luxury and cultural authenticity.",
        challenge: "Communicating the hotel's cultural identity — the irreverent, joyful spirit of Kalakuta — through architectural visualization, a medium that tends toward stiff formality.",
        solution: "People were central in every image, carefully cast and posed to suggest movement and gathering rather than the empty-room convention of most hospitality renders. Material colours were pushed warm — amber timber, terracotta tile, hand-thrown pottery — to evoke the richness of the reference.",
        tags: ["Hospitality", "Interior Renders", "Cultural Identity"],
        accentColor: "from-[#0a0c10] via-[#12161e] to-[#060810]",
        svgKey: "hotel",
        images: ARCH_IMGS.hotel,
      },
    ],
  },
  {
    slug: "animation",
    label: "Animation",
    title: "Animation",
    subtitle: "Motion through space and time",
    description:
      "Cinematic walkthroughs, aerial fly-overs, and construction-sequence animations that bring architectural proposals to life before a single foundation is poured. Used for planning submissions, investor decks, public engagement campaigns, and social media presence.",
    tools: ["3ds Max", "Unreal Engine 5", "Twinmotion", "After Effects", "DaVinci Resolve", "Cinema 4D"],
    index: "03",
    projects: [
      {
        id: "anim-01",
        title: "Graceland Estate",
        location: "Lagos, Nigeria",
        year: "2023",
        area: "3 min 40 sec",
        category: "Commercial",
        client: "Graceland Estate Ltd",
        status: "Delivered",
        description: "This is a 3d animation of Graceland Estate, a residential estate in Lagos, Nigeria.",
        challenge: "To create a walkthrough that communicates the estate's modern design and amenities.",
        solution: "The opening sequence begins with an aerial over Victoria Island at dawn, the camera pulling back to reveal the tower against the brightening Atlantic. The film was graded with warm, golden tones throughout and scored with a custom composition blending contemporary Afrobeat with orchestral undertones.",
        tags: ["Investor Film", "4K", "Sound Design"],
        accentColor: "from-[#1a100a] via-[#2d1800] to-[#0e0a04]",
        svgKey: "tower",
        images: ARCH_IMGS.animationOne,
      },
      {
        id: "anim-03",
        title: "Medmac Pharmacy",
        location: "Lagos, Nigeria",
        year: "2022",
        area: "2 min 10 sec",
        category: "Commercial",
        client: "Medmac Pharmacy",
        status: "Delivered",
        description: "This animation showcases the interior and exterior of the pharmacy, highlighting its modern design and amenities.",
        challenge: "To create a walkthrough that communicates the pharmacy's modern design and amenities.",
        solution: "The film uses ambient sound only — wind, water, birdsong, distant city — and moves at a walking pace. Camera cuts are replaced by slow dissolves. The colour grade is deliberately muted until the final sequence, when the garden fills with people and life.",
        tags: ["Commercial", "Interior Renders", "Exterior Renders"],
        accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
        svgKey: "waterfront",
        images: ARCH_IMGS.animationTwo,
      },
      // {
      //   id: "anim-04",
      //   title: "Biafra Memory Gardens — Heritage Film",
      //   location: "Nsukka, Nigeria",
      //   year: "2019",
      //   area: "8 min 15 sec",
      //   category: "Memorial",
      //   client: "Biafra Memory Foundation",
      //   status: "Award-winning",
      //   description: "Long-form heritage film tracing the visitor's journey through the landscape from arrival to the central memorial chamber. Won a public communications award.",
      //   challenge: "A film about a historical atrocity must honour the gravity of the subject while creating something that people will actually watch — and that will move them to support the project's funding campaign.",
      //   solution: "Archival photography and documentary testimony were woven into the architectural animation using match-cuts between historical images and the rendered spaces. The garden architecture was designed to frame and contain these historical moments as the visitor moves through it.",
      //   tags: ["Heritage", "Long-form", "Award-winning"],
      //   accentColor: "from-[#100c08] via-[#1e1608] to-[#0c0a04]",
      //   svgKey: "precinct",
      //   images: ARCH_IMGS.precinct,
      // },
    ],
  },
  {
    slug: "construction-drawings",
    label: "Construction Drawings",
    title: "Construction Drawings",
    subtitle: "Precision documentation for builders",
    description:
      "Full drawing packages — plans, sections, elevations, construction details, and specifications — produced to COREN and NEC standards. Coordinated drawing sets across all disciplines, ready for contractor tender, site supervision, and regulatory submission.",
    tools: ["AutoCAD", "Revit", "MicroStation", "Bluebeam Revu", "Navisworks", "Adobe Acrobat"],
    index: "04",
    projects: [
      {
        id: "cd-01",
        title: "Enugu State Parliament Extension",
        location: "Enugu, Nigeria",
        year: "2020",
        area: "22,000 m²",
        category: "Civic",
        client: "Enugu State Government",
        status: "Completed",
        description: "Complete RIBA Stage 4 drawing package: 380 sheets covering architectural, structural, mechanical, electrical, plumbing, and specialist sub-systems.",
        challenge: "A government project with political oversight, multiple ministries as stakeholders, and three separate contractor packages required a drawing management system that could handle simultaneous revisions without version conflicts.",
        solution: "A Bluebeam Studio session was established as the single source of truth, with an automated revision cloud system that flagged every change to all discipline leads simultaneously. The 380-sheet package was delivered three weeks ahead of programme.",
        tags: ["Government", "Stage 4", "380 Sheets"],
        accentColor: "from-[#0a0e18] via-[#0e1626] to-[#060a12]",
        svgKey: "parliament",
        images: ARCH_IMGS.parliament,
      },
      {
        id: "cd-02",
        title: "Lekki Phase 2 Business Precinct",
        location: "Lagos, Nigeria",
        year: "2022",
        area: "38,000 m²",
        category: "Mixed-Use",
        client: "Lekki Free Zone Development Company",
        status: "Under Construction",
        description: "Mixed-use precinct drawing set spanning three towers, shared basement, retail podium, and public realm. Full NBS specification and O&M manual delivered alongside drawings.",
        challenge: "Three towers sharing a basement slab required structural, geotechnical, MEP, and architectural drawings to be coordinated to sub-10mm accuracy across a 200-metre plan.",
        solution: "All disciplines worked within a federated Revit environment on a shared origin point. Weekly coordination meetings used live Navisworks models, and all drawing issue was automated through Revit's sheet management system eliminating manual PDF production errors.",
        tags: ["Mixed-Use", "NBS Specification", "O&M Manual"],
        accentColor: "from-[#1a100a] via-[#2d1800] to-[#0e0a04]",
        svgKey: "precinct",
        images: ARCH_IMGS.precinct,
      },
      {
        id: "cd-03",
        title: "Ikoyi Residence VII",
        location: "Lagos, Nigeria",
        year: "2023",
        area: "1,800 m²",
        category: "Residential",
        client: "Private Client",
        status: "Completed",
        description: "Luxury private residence package — detailed joinery drawings, bespoke ironmongery schedules, stone cladding details, and pool engineering coordination.",
        challenge: "A client of this calibre expected every bespoke element — floor-to-ceiling joinery, hand-crafted ironmongery, stone slabs matched across room transitions — to be documented to a standard that guaranteed the builder could price and build it without a single query.",
        solution: "Each joinery unit was drawn at 1:5 scale with full material and finish call-outs. Ironmongery was specified to a bespoke schedule cross-referenced to every door and window. Stone slabs were drawn showing actual slab layout with book-matching and grain direction noted.",
        tags: ["Luxury", "Joinery", "Bespoke Details"],
        accentColor: "from-[#120808] via-[#200e10] to-[#0e0608]",
        svgKey: "residence",
        images: ARCH_IMGS.residence,
      },
      {
        id: "cd-04",
        title: "Zuma Rock Cultural Centre",
        location: "Abuja, Nigeria",
        year: "2022",
        area: "18,400 m²",
        category: "Cultural",
        client: "FCT Area Council",
        status: "Completed",
        description: "Heritage and cultural building with complex conservation requirements. Drawing set developed in close coordination with NCMM and state heritage authorities.",
        challenge: "Cultural buildings in Nigeria must be documented in a way that satisfies both the technical contractor and the heritage authority — two audiences with fundamentally different drawing literacy requirements.",
        solution: "A dual-issue drawing strategy was developed: a full technical set for the contractor, and a simplified heritage narrative set for the NCMM, both derived from the same Revit model to ensure permanent coordination.",
        tags: ["Heritage", "Conservation", "NCMM"],
        accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
        svgKey: "cultural",
        images: ARCH_IMGS.cultural,
      },
    ],
  },
  {
    slug: "presentation-drawings",
    label: "Presentation Drawings",
    title: "Presentation Drawings",
    subtitle: "Ideas made visible and compelling",
    description:
      "Curated design presentation packages — concept diagrams, analysis drawings, design-intent sections, masterplan axonometrics, and layout compositions tailored for client briefings, competitions, and publications.",
    tools: ["Adobe Illustrator", "InDesign", "Photoshop", "SketchUp", "QGIS", "Figma"],
    index: "05",
    projects: [
      {
        id: "pd-01",
        title: "Box and Earth Solutions",
        location: "Lagos, Nigeria",
        year: "2025",
        area: "Lagos",
        category: "Urban",
        client: "Box and Earth Solutions",
        status: "Competition",
        description: "Presentation drawings for a competition submission.",
        challenge: "To create a presentation that could stand out in a competition with 34 entries.",
        solution: "A visual language was developed where every diagram used the same graphic palette, making information instantly comparable across boards. The narrative was structured as a journey from problem to solution, with the final board showing a single compelling image of the completed waterfront.",
        tags: ["Competition","12 Boards", "Urban Design"],
        accentColor: "from-[#100c08] via-[#1e1608] to-[#0c0a04]",
        svgKey: "waterfront",
        images: ARCH_IMGS.presentationOne,
      },
      {
        id: "pd-02",
        title: "Obrutche",
        location: "Abuja, Nigeria",
        year: "2023",
        area: "Client Briefing",
        category: "Civic",
        client: "Private Client",
        status: "Approved",
        description: "Presidential client briefing pack — six large-format boards distilling the design concept, cultural references, spatial sequence, and materiality for federal approval.",
        challenge: "A presidential briefing has a maximum audience attention window of twelve minutes. The drawings had to communicate a 24,000 m² cultural building — its civic aspiration, its cultural references, its technical credibility — in that time.",
        solution: "Each board was designed to deliver one clear message, with all supporting information subordinated to that message. Typography was scaled for a boardroom presentation, not close reading. The colour palette matched the building's material intentions, making the drawings feel like the building.",
        tags: ["Presidential Brief", "Civic", "Narrative Design"],
        accentColor: "from-[#0a0e18] via-[#0e1626] to-[#060a12]",
        svgKey: "arts",
        images: ARCH_IMGS.presentationTwo,
      },
      // {
      //   id: "pd-03",
      //   title: "EndSARS Memorial Garden",
      //   location: "Lagos, Nigeria",
      //   year: "2022",
      //   area: "Exhibition",
      //   category: "Memorial",
      //   client: "Lagos State Government",
      //   status: "Exhibited",
      //   description: "Exhibition drawings for the Lagos Architecture Biennial. Large-scale diagrammatic drawings exploring the relationship between trauma, memory, and landscape architecture.",
      //   challenge: "Exhibition drawings must work at two scales simultaneously — legible as wall graphics from five metres, and rewarding to read up close for those who choose to engage more deeply.",
      //   solution: "A layered drawing system was developed where the primary diagram reads clearly at distance, and secondary annotation, historical reference, and material detail emerges on close inspection. Drawings were printed at 2m × 1.5m on matte cotton rag.",
      //   tags: ["Biennial", "Exhibition", "Memorial"],
      //   accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
      //   svgKey: "cultural",
      //   images: ARCH_IMGS.cultural,
      // },
      {
        id: "pd-04",
        title: "Avenue Row",
        location: "Lagos, Nigeria",
        year: "2025",
        area: "Publication",
        category: "Landscape",
        client: "Private Client",
        status: "Published",
        description: "Private residential landscape design for a client in Lagos, Nigeria.",
        challenge: "To create a presentation that could stand out in a competition with 34 entries.",
        solution: "A visual language was developed where every diagram used the same graphic palette, making information instantly comparable across boards. The narrative was structured as a journey from problem to solution, with the final board showing a single compelling image of the completed waterfront.",
        tags: ["Publication", "Hand-drafted", "Landscape"],
        accentColor: "from-[#120808] via-[#200e10] to-[#0e0608]",
        svgKey: "library",
        images: ARCH_IMGS.avenueRow,
      },
    ],
  },
  {
    slug: "interior-design",
    label: "Interior Design",
    title: "Interior Design",
    subtitle: "Space felt from the inside",
    description:
      "Complete interior environments rooted in West African craft traditions and contemporary comfort. Spatial planning, material palette curation, furniture selection, lighting design, and full FF&E specifications. Every interior begins with a question: what is the particular feeling this space must create?",
    tools: ["AutoCAD", "Revit", "SketchUp", "V-Ray", "3ds Max", "Adobe Suite"],
    index: "06",
    projects: [
      {
        id: "int-01",
        title: "Ikoyi Residence VII",
        location: "Lagos, Nigeria",
        year: "2023",
        area: "1,800 m²",
        category: "Residential",
        client: "Private Client",
        status: "Completed",
        description: "Full FF&E package for a six-bedroom Ikoyi residence. Material palette anchored in Abeokuta granite, Akwete woven textile panels, and hand-thrown Abuja pottery.",
        challenge: "A client who travels internationally and has seen the best of global interior design wanted something that was unambiguously Nigerian in character without any of the clichés — no Afrocentric kitsch, no pastiche traditionalism.",
        solution: "The brief was answered through material authenticity rather than visual reference. Abeokuta granite, Akwete handloom textile, Abuja pottery, Bida glasswork — all sourced directly from their makers, with the making process informing the design of each custom piece.",
        tags: ["Luxury", "FF&E", "West African Craft"],
        accentColor: "from-[#120808] via-[#200e10] to-[#0e0608]",
        svgKey: "residence",
        images: ARCH_IMGS.residence,
      },
      {
        id: "int-02",
        title: "Kalakuta Suite Hotel",
        location: "Port Harcourt, Nigeria",
        year: "2021",
        area: "6,400 m²",
        category: "Hospitality",
        client: "Kalakuta Hospitality Group",
        status: "Completed",
        description: "Full interior design for a 48-suite boutique hotel. Each suite's material palette draws from a different era of Nigerian music culture.",
        challenge: "Designing 48 suites that are each distinctively themed without descending into theme-park historicism — the Fela suite cannot feel like a costume; it must feel like the music.",
        solution: "Rather than reproducing Kalakuta iconography literally, each suite's material and lighting scheme was designed to evoke the emotional quality of its musical era. The Fela suite is warm amber and raw concrete — the energy of the Republic. The Afrobeats suite is layered, complex, joyful.",
        tags: ["Hospitality", "Cultural Identity", "48 Suites"],
        accentColor: "from-[#0a0c10] via-[#12161e] to-[#060810]",
        svgKey: "hotel",
        images: ARCH_IMGS.hotel,
      },
      {
        id: "int-03",
        title: "Nnamdi Azikiwe Office HQ",
        location: "Abuja, Nigeria",
        year: "2021",
        area: "4,200 m²",
        category: "Corporate",
        client: "Azikiwe Group",
        status: "Completed",
        description: "Corporate headquarters channelling Nigeria's first president through Iroko timber, polished concrete, and hand-woven Aso-Oke wall panels.",
        challenge: "A corporate headquarters must project stability and authority without feeling oppressive. For a Nigerian corporation with historical roots in the independence era, the interior also had to carry a sense of pride without nationalism becoming pomposity.",
        solution: "Dark Iroko timber panelling — one of Nigeria's most noble materials — was used throughout the executive floors, its grain the primary decorative element. Aso-Oke weave panels in the boardroom provided texture and cultural identity at the most important moment of arrival.",
        tags: ["Corporate", "Iroko Timber", "Heritage"],
        accentColor: "from-[#08100e] via-[#0d1a14] to-[#060e0c]",
        svgKey: "arts",
        images: ARCH_IMGS.arts,
      },
    ],
  },
];

export function getService(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug);
}
